EXIT_SUCCESS = 0
EXIT_FAILURE = 1
EXIT_GENERAL_PROGRAM_FAILURES = 2

MINIMUM_CUTOFF_DIST = 0.00
MINIMUM_CUTOFF_ANGLE = 0.00
MAXIMUM_CUTOFF_ANGLE = 360.00
MINIMUM_VERTICES = 3

MAXIMUM_WORKERS = 15

LEN_PDB_CODE = 4

DEFAULT_MONGO_HOST = 'localhost'
DEFAULT_MONGO_PORT = 27017
